/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSyahriyahRouteImport } from './routes/_authenticated/syahriyah'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin-users'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSessionExpiredRouteImport } from './routes/(auth)/session-expired'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedStudentsIdSantriRouteImport } from './routes/_authenticated/students/$idSantri'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedPaymentsMethodsRouteImport } from './routes/_authenticated/payments/methods'
import { Route as AuthenticatedPaymentsConsumersRouteImport } from './routes/_authenticated/payments/consumers'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events/new'
import { Route as AuthenticatedEventsIdRouteImport } from './routes/_authenticated/events/$id'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedStoreProductsIndexRouteImport } from './routes/_authenticated/store/products/index'
import { Route as AuthenticatedStoreProductsNewRouteImport } from './routes/_authenticated/store/products/new'
import { Route as AuthenticatedStoreProductsIdRouteImport } from './routes/_authenticated/store/products/$id'
import { Route as AuthenticatedPaymentsInvoicesIdRouteImport } from './routes/_authenticated/payments/invoices/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSyahriyahRoute = AuthenticatedSyahriyahRouteImport.update({
  id: '/syahriyah',
  path: '/syahriyah',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSessionExpiredRoute = authSessionExpiredRouteImport.update({
  id: '/(auth)/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPaymentsRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)
const AuthenticatedStudentsIdSantriRoute =
  AuthenticatedStudentsIdSantriRouteImport.update({
    id: '/$idSantri',
    path: '/$idSantri',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPaymentsMethodsRoute =
  AuthenticatedPaymentsMethodsRouteImport.update({
    id: '/methods',
    path: '/methods',
    getParentRoute: () => AuthenticatedPaymentsRoute,
  } as any)
const AuthenticatedPaymentsConsumersRoute =
  AuthenticatedPaymentsConsumersRouteImport.update({
    id: '/consumers',
    path: '/consumers',
    getParentRoute: () => AuthenticatedPaymentsRoute,
  } as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedEventsRoute,
} as any)
const AuthenticatedEventsIdRoute = AuthenticatedEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEventsRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoreProductsIndexRoute =
  AuthenticatedStoreProductsIndexRouteImport.update({
    id: '/store/products/',
    path: '/store/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoreProductsNewRoute =
  AuthenticatedStoreProductsNewRouteImport.update({
    id: '/store/products/new',
    path: '/store/products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoreProductsIdRoute =
  AuthenticatedStoreProductsIdRouteImport.update({
    id: '/store/products/$id',
    path: '/store/products/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsInvoicesIdRoute =
  AuthenticatedPaymentsInvoicesIdRouteImport.update({
    id: '/invoices/$id',
    path: '/invoices/$id',
    getParentRoute: () => AuthenticatedPaymentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/session-expired': typeof authSessionExpiredRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin-users': typeof AuthenticatedAdminUsersRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/syahriyah': typeof AuthenticatedSyahriyahRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/payments/consumers': typeof AuthenticatedPaymentsConsumersRoute
  '/payments/methods': typeof AuthenticatedPaymentsMethodsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/students/$idSantri': typeof AuthenticatedStudentsIdSantriRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/payments/invoices/$id': typeof AuthenticatedPaymentsInvoicesIdRoute
  '/store/products/$id': typeof AuthenticatedStoreProductsIdRoute
  '/store/products/new': typeof AuthenticatedStoreProductsNewRoute
  '/store/products/': typeof AuthenticatedStoreProductsIndexRoute
}
export interface FileRoutesByTo {
  '/session-expired': typeof authSessionExpiredRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin-users': typeof AuthenticatedAdminUsersRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/syahriyah': typeof AuthenticatedSyahriyahRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/payments/consumers': typeof AuthenticatedPaymentsConsumersRoute
  '/payments/methods': typeof AuthenticatedPaymentsMethodsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/students/$idSantri': typeof AuthenticatedStudentsIdSantriRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/payments/invoices/$id': typeof AuthenticatedPaymentsInvoicesIdRoute
  '/store/products/$id': typeof AuthenticatedStoreProductsIdRoute
  '/store/products/new': typeof AuthenticatedStoreProductsNewRoute
  '/store/products': typeof AuthenticatedStoreProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/session-expired': typeof authSessionExpiredRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/admin-users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/events': typeof AuthenticatedEventsRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/syahriyah': typeof AuthenticatedSyahriyahRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/events/$id': typeof AuthenticatedEventsIdRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/payments/consumers': typeof AuthenticatedPaymentsConsumersRoute
  '/_authenticated/payments/methods': typeof AuthenticatedPaymentsMethodsRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/students/$idSantri': typeof AuthenticatedStudentsIdSantriRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/payments/invoices/$id': typeof AuthenticatedPaymentsInvoicesIdRoute
  '/_authenticated/store/products/$id': typeof AuthenticatedStoreProductsIdRoute
  '/_authenticated/store/products/new': typeof AuthenticatedStoreProductsNewRoute
  '/_authenticated/store/products/': typeof AuthenticatedStoreProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/session-expired'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin-users'
    | '/events'
    | '/notifications'
    | '/payments'
    | '/students'
    | '/syahriyah'
    | '/errors/$error'
    | '/events/$id'
    | '/events/new'
    | '/payments/consumers'
    | '/payments/methods'
    | '/settings/appearance'
    | '/students/$idSantri'
    | '/events/'
    | '/payments/'
    | '/settings/'
    | '/payments/invoices/$id'
    | '/store/products/$id'
    | '/store/products/new'
    | '/store/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/session-expired'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin-users'
    | '/notifications'
    | '/students'
    | '/syahriyah'
    | '/'
    | '/errors/$error'
    | '/events/$id'
    | '/events/new'
    | '/payments/consumers'
    | '/payments/methods'
    | '/settings/appearance'
    | '/students/$idSantri'
    | '/events'
    | '/payments'
    | '/settings'
    | '/payments/invoices/$id'
    | '/store/products/$id'
    | '/store/products/new'
    | '/store/products'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/session-expired'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/admin-users'
    | '/_authenticated/events'
    | '/_authenticated/notifications'
    | '/_authenticated/payments'
    | '/_authenticated/students'
    | '/_authenticated/syahriyah'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/events/$id'
    | '/_authenticated/events/new'
    | '/_authenticated/payments/consumers'
    | '/_authenticated/payments/methods'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/students/$idSantri'
    | '/_authenticated/events/'
    | '/_authenticated/payments/'
    | '/_authenticated/settings/'
    | '/_authenticated/payments/invoices/$id'
    | '/_authenticated/store/products/$id'
    | '/_authenticated/store/products/new'
    | '/_authenticated/store/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSessionExpiredRoute: typeof authSessionExpiredRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/syahriyah': {
      id: '/_authenticated/syahriyah'
      path: '/syahriyah'
      fullPath: '/syahriyah'
      preLoaderRoute: typeof AuthenticatedSyahriyahRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-users': {
      id: '/_authenticated/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/session-expired': {
      id: '/(auth)/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof authSessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/students/$idSantri': {
      id: '/_authenticated/students/$idSantri'
      path: '/$idSantri'
      fullPath: '/students/$idSantri'
      preLoaderRoute: typeof AuthenticatedStudentsIdSantriRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/payments/methods': {
      id: '/_authenticated/payments/methods'
      path: '/methods'
      fullPath: '/payments/methods'
      preLoaderRoute: typeof AuthenticatedPaymentsMethodsRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
    '/_authenticated/payments/consumers': {
      id: '/_authenticated/payments/consumers'
      path: '/consumers'
      fullPath: '/payments/consumers'
      preLoaderRoute: typeof AuthenticatedPaymentsConsumersRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/events/$id': {
      id: '/_authenticated/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AuthenticatedEventsIdRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store/products/': {
      id: '/_authenticated/store/products/'
      path: '/store/products'
      fullPath: '/store/products/'
      preLoaderRoute: typeof AuthenticatedStoreProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store/products/new': {
      id: '/_authenticated/store/products/new'
      path: '/store/products/new'
      fullPath: '/store/products/new'
      preLoaderRoute: typeof AuthenticatedStoreProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store/products/$id': {
      id: '/_authenticated/store/products/$id'
      path: '/store/products/$id'
      fullPath: '/store/products/$id'
      preLoaderRoute: typeof AuthenticatedStoreProductsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/invoices/$id': {
      id: '/_authenticated/payments/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/payments/invoices/$id'
      preLoaderRoute: typeof AuthenticatedPaymentsInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedEventsRouteChildren {
  AuthenticatedEventsIdRoute: typeof AuthenticatedEventsIdRoute
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
}

const AuthenticatedEventsRouteChildren: AuthenticatedEventsRouteChildren = {
  AuthenticatedEventsIdRoute: AuthenticatedEventsIdRoute,
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
}

const AuthenticatedEventsRouteWithChildren =
  AuthenticatedEventsRoute._addFileChildren(AuthenticatedEventsRouteChildren)

interface AuthenticatedPaymentsRouteChildren {
  AuthenticatedPaymentsConsumersRoute: typeof AuthenticatedPaymentsConsumersRoute
  AuthenticatedPaymentsMethodsRoute: typeof AuthenticatedPaymentsMethodsRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedPaymentsInvoicesIdRoute: typeof AuthenticatedPaymentsInvoicesIdRoute
}

const AuthenticatedPaymentsRouteChildren: AuthenticatedPaymentsRouteChildren = {
  AuthenticatedPaymentsConsumersRoute: AuthenticatedPaymentsConsumersRoute,
  AuthenticatedPaymentsMethodsRoute: AuthenticatedPaymentsMethodsRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedPaymentsInvoicesIdRoute: AuthenticatedPaymentsInvoicesIdRoute,
}

const AuthenticatedPaymentsRouteWithChildren =
  AuthenticatedPaymentsRoute._addFileChildren(
    AuthenticatedPaymentsRouteChildren,
  )

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsIdSantriRoute: typeof AuthenticatedStudentsIdSantriRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsIdSantriRoute: AuthenticatedStudentsIdSantriRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRouteWithChildren
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedSyahriyahRoute: typeof AuthenticatedSyahriyahRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedStoreProductsIdRoute: typeof AuthenticatedStoreProductsIdRoute
  AuthenticatedStoreProductsNewRoute: typeof AuthenticatedStoreProductsNewRoute
  AuthenticatedStoreProductsIndexRoute: typeof AuthenticatedStoreProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRouteWithChildren,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedSyahriyahRoute: AuthenticatedSyahriyahRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedStoreProductsIdRoute: AuthenticatedStoreProductsIdRoute,
  AuthenticatedStoreProductsNewRoute: AuthenticatedStoreProductsNewRoute,
  AuthenticatedStoreProductsIndexRoute: AuthenticatedStoreProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSessionExpiredRoute: authSessionExpiredRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
